version: '3.8'

networks:
  auctionnetwork:

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27019:27017
    container_name: mongodb 
    hostname: mongodb
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - auctionnetwork

  userservice:
    image: rasmusdd/userservice3-image:1.0.0
    ports:
      - 80:8080
    depends_on: 
      - mongodb
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bruger
    container_name: userservice 
    hostname: userservice
    networks:
      - auctionnetwork

  catalogservice:
    image: furk0402/catalogservice-image:latest
    ports:
      - 81:8080 # Assuming your Catalog API listens on port 8080 internally
    depends_on:
      - mongodb
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Katalog
    container_name: catalogservice
    hostname: catalogservice
    networks:
      - auctionnetwork

volumes:
  mongodb_data_container:
